repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
        stages: [pre-commit]
      - id: ruff-format
        name: ruff (auto-fix)
        args: []
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
          - "--no-strict-optional"
          - "--allow-untyped-defs"
          - "--allow-incomplete-defs"
          - "--allow-untyped-calls"
          - "--disable-error-code=name-defined"
          - "--disable-error-code=attr-defined"
          - "--disable-error-code=arg-type"
          - "--disable-error-code=return-value"
          - "--disable-error-code=assignment"
          - "--disable-error-code=operator"
          - "--disable-error-code=misc"
          - "--disable-error-code=index"
          - "--disable-error-code=call-arg"
          - "--disable-error-code=type-arg"
          - "--disable-error-code=no-untyped-def"
          - "--disable-error-code=no-untyped-call"
          - "--disable-error-code=no-any-return"
          - "--disable-error-code=var-annotated"
          - "--disable-error-code=return"
        additional_dependencies:
          - tomli
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]
