repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
        stages: [pre-commit]
        exclude: ^src/arc_dslearn/arc_dsl/
      - id: ruff-format
        name: ruff (auto-fix)
        args: []
        stages: [pre-commit]
        exclude: ^src/arc_dslearn/arc_dsl/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
        additional_dependencies:
          - tomli
          - types-requests
        entry: uv run mypy src/
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]
