repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        name: ruff (lint)
        args: []
        stages: [pre-commit]
      - id: ruff-format
        name: ruff (auto-fix)
        args: ["--fix"]
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
        additional_dependencies:
          - tomli
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]
