[project]
name = "arc-dslearn"
version = "0.0.1"
description = "ARC DSL experiments"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[tool.uv]
# uv-specific settings (optional)
python = "3.11"          # interpreter pinned for everyone