name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2   # lightweight lock installer for Hatch, Poetry & PEP 517
    - name: Install
      run: |
        pip install --upgrade pip
        pip install 'hatchling>=1.24' uv
        uv pip install -e .[dev]
    - name: Lint & format
      run: ruff check --output-format github --exclude 'src/arc_dslearn/arc_dsl' .
    - name: Type-check
      run: mypy src tests --exclude 'src/arc_dslearn/arc_dsl'
    - name: Test
      run: pytest -q
